### ISSUE TITLE
Can't Find the Trained Model from Provided Link

### ISSUE THREAD

**Issue by EverleyTseng** [breadbread1984/c3d#1]
The trained model no longer exists! Can you provide a new link to traine-model?

**Comment by sathishraja92** [comment]
@breadbread1984  trained model is not available in the link you provided. where can I find the trained model?

**Comment by breadbread1984** [comment]
It still there. I checked it again. does it take too long to open the link?

**Comment by bravo325806** [comment]
I open the Baidu link but it not exists. can you provide a trained model again?

**Comment by breadbread1984** [comment]
the link is OK in mainland. Maybe baidu service is not available in Taiwan. I don't have a stable way to tunnel to google drive yet. Do you have any suggestion on how I can share it to you?

**Comment by bravo325806** [comment]
you're right, the taiwan ip is blocked from baidu, I use google extension kit(vpn), this can solve problem, thanks for your reply.
